### ISSUE TITLE
function ' getQuery()' missing optional paramaters ($modelAlias = null, $criteria = null)

### ISSUE THREAD

**Issue by nibsirahsieu** [emiliomg/PropelProviderBehavior#1]

**Comment by emiliomg** [comment]
Wow, I did not think anyone would stumble upon this behavior. How did you find this, if I may ask?
As for the issue: you are right, I will fix this in a couple of hours.

**Comment by emiliomg** [comment]
Fixed in 1.1.2

**Comment by nibsirahsieu** [comment]
your propel issue brought me here :)
